version: 2

updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/Toronto"
    open-pull-requests-limit: 10
    target-branch: "dev"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/Toronto"
    open-pull-requests-limit: 10
    target-branch: "dev"
